export const characters = [
  {
    classification: "Acolyte",
    name: "",
    str: 10,
    dex: 10,
    wil: 14,
    hp: 4,
    attack: "mace (d8) or ceremonial dagger (d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Holy men and women bound to a particular deity. Normally travel in groups of 4+. Holy Symbol (Ward once per day)"
  },
  {
    classification: "Ape, White",
    name: "",
    str: 14,
    dex: 10,
    wil: 10,
    hp: 5,
    attack: "claws (d6+d6), rocks (d6, Blast)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Albino gorillas with nocturnal habits. Defend their territory with threatening gestures, followed by sudden violence."
  },
  {
    classification: "Aranea",
    name: "",
    str: 10,
    dex: 12,
    wil: 15,
    hp: 6,
    attack: "bite (d6), two random spellbooks",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "6’ long, intelligent spiders of greenish-black coloration. Have an odd lump on the back, housing its large brain. Two front legs have digits, allowing an aranea to grasp tools. Dwell in web-filled lairs where they conduct magical research. Scared of fire, avoid spells of such effect.\nCreatures caught in its webs are entangled and unable to move. Breaking free requires an STR save."
  },
  {
    classification: "Bandit",
    name: "",
    str: 11,
    dex: 14,
    wil: 12,
    hp: 4,
    attack: "dagger (d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Thieves who value wealth over all else. Use disguises, stealth, and trickery to surprise victims."
  },
  {
    classification: "Basilisk",
    name: "",
    str: 12,
    dex: 13,
    wil: 13,
    hp: 10,
    attack: "bite (d10)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Long, serpentine lizards that nest deep below the earth or in brambles just underfoot.\nGaze: A PC meeting the Basilisk’s gaze must make a WIL save or turn instantly to stone. Its reflection is harmless.\nFighting a Basilisk without meeting its gaze is difficult (direct attacks are Impaired)."
  },
  {
    classification: "Bat, Vampire",
    name: "",
    str: 6,
    dex: 14,
    wil: 10,
    hp: 3,
    attack: "bite (d8)",
    description: "Large, nocturnal mammals that feed on the blood of their victims. Unaffected by darkness or blinding effects. Loud noises and holy rituals may frighten them. Critical Damage: Recovers full STR and HP if the target has blood."
  },
  {
    classification: "Bear, Black",
    name: "",
    str: 14,
    dex: 12,
    wil: 6,
    hp: 6,
    attack: "claws (d6+d6), bite (d8)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "4’ tall bears (twice that much if standing) that subsist mostly on berries and roots. Drawn to campsites in search of food. Aggressive if cornered or feel that their young are threatened."
  },
  {
    classification: "Beetle, Tiger",
    name: "",
    str: 6,
    dex: 12,
    wil: 6,
    hp: 3,
    attack: "bite (d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "4’ long striped carnivorous insect with powerful mandibles. Prefers smaller prey but will not shy from hunting the occasional humanoid."
  },
  {
    classification: "Berserker",
    name: "",
    str: 14,
    dex: 13,
    wil: 15,
    hp: 10,
    attack: "twin axes (d8+d8)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Ruthless warriors that derive their power from the skins they wear: bears, wolves, boards, etc. Ignores the Morale rule and is never treated as part of a detachment. Rage: The Berserker enters a state of pure fury, their attacks gaining the Enhanced and Blast quality until they take STR damage."
  },
  {
    classification: "Black Pudding",
    name: "",
    str: 11,
    dex: 5,
    wil: 3,
    hp: 12,
    attack: "devouring touch (d8)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Giant, brainless blobs of black jelly driven only by their insatiable hunger. Moves along walls and across ceilings. Squeeze through holes and cracks with ease. Immune to mundane attacks, save fire. Normal attacks splits the Black Pudding, creating two Puddings that share HP and STR. Dissolve: On Critical Damage, armored targets lose 1 Armor point. STR loss to unarmored targets is permanent."
  },
  {
    classification: "Blink Dog",
    name: "",
    str: 11,
    dex: 14,
    wil: 5,
    hp: 5,
    attack: "bite (d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Intelligent, wild dogs that travel in packs. After each attack, they may teleport a safe distance away."
  },
  {
    classification: "Boar",
    name: "",
    str: 12,
    dex: 6,
    wil: 10,
    hp: 3,
    attack: "tusks (d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Omnivorous wild boars that dwell primarily in forests. Not naturally aggressive, but dangerous if disturbed. Critical Damage: Gores its victims, causing great loss of blood."
  },
  {
    classification: "Brigand",
    name: "",
    str: 12,
    dex: 12,
    wil: 9,
    hp: 4,
    attack: "shortsword (d6) or short bow (d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Outlaws and mercenaries who raid settlements and ambush travelers. Travel in large groups of at least one detachment. A detachment always travels with one leader wearing chainmail or similar (2 Armor) and a longsword (d8) or crossbow (d8). When testing Morale, save using the leader’s WIL (13). If the leader dies, the Brigands will flee."
  },
  {
    classification: "Bugbear",
    name: "",
    str: 14,
    dex: 12,
    wil: 11,
    hp: 4,
    attack: "club (d8, bulky)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Large, goblinoids covered in animal-like hair. Prefers stealth and trickery to gain an advantage."
  },
  {
    classification: "Camel",
    str: 12,
    dex: 13,
    wil: 4,
    hp: 3,
    attack: "bite (d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Beasts of burden native to dry, arid lands. Can survive without water for weeks at a time. Moves through sand and broken ground without difficulty."
  },
  {
    classification: "Cat, Lion",
    name: "",
    str: 12,
    dex: 12,
    wil: 11,
    hp: 5,
    attack: "bite (d10), claws (d6+d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Hunts in a pride of at least 4. Lives in the savannahs or other similarly dry lands. Carnivorous. Only hunts humans if desperately hungry or in clear advantage. Blood-sense: Can follow bleeding prey over great distances."
  },
  {
    classification: "Cave Locust",
    name: "",
    str: 6,
    dex: 12,
    wil: 6,
    hp: 2,
    attack: "bite (d4)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Giant, herbivorous crickets that dwell in caves. Blends into stone due to their natural coloration. Emits loud shrieks when threatened that can be heard from very far away. Immune to most types of poison."
  },
  {
    classification: "Centaur",
    name: "",
    str: 14,
    dex: 12,
    wil: 6,
    hp: 6,
    attack: "spear (d8) or short bow (d6)",
    description: "Creatures with the lower body and legs of a horse and the upper body, arms and head of a humanoid. Uses their great speed to hunt for food in the forest and plains."
  },
  {
    classification: "Centipede, Giant",
    name: "",
    str: 6,
    dex: 0,
    wil: 3,
    hp: 1,
    attack: "sting (d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "2’ long centipedes that live in damp, underground places. Generally shy, but will attack if approached. Critical Damage: the venom renders the target deprived for up to 10 days (save STR once a day to recover)."
  },
  {
    classification: "Chimera",
    name: "",
    str: 14,
    dex: 0,
    wil: 0,
    hp: 10,
    attack: "bite and gore (d10+d10), fire breath (d12, Blast)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "A three-headed flying aberration. A hybrid of lion, goat, and dragon. Created through powerful magic, these creatures can be bound to a master or roaming free."
  },
  {
    classification: "Cobblehounds",
    name: "",
    str: 14,
    dex: 1,
    wil: 8,
    hp: 12,
    attack: "bite (d10)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Immobile constructs typically used as guardians to great tombs or artifacts. Unaffected by mundane persuasion techniques, but does love a good bone."
  },
  {
    classification: "Cockatrice",
    name: "",
    str: 8,
    dex: 14,
    wil: 0,
    hp: 5,
    attack: "beak (d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Small creatures resembling chickens with reptilian features. Notably agile and hard to pin down, their greatest enemy is the weasel. Critical Damage: the victim is turned to stone until the Cockatrice is killed."
  },
  {
    classification: "Bone Construct",
    name: "",
    str: 15,
    dex: 0,
    wil: 8,
    hp: 8,
    attack: "sharpened arms (d8, Blast)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "6’ tall humanoid constructs made of bone and sorcery. Four-armed, with sharpened ends spread around their torso. Mindless guardians, they simply detect and attack any living creature besides their creator. Mundane attacks are Impaired against the construct."
  },
  {
    classification: "Dwarf",
    name: "",
    str: 14,
    dex: 0,
    wil: 0,
    hp: 4,
    armor: 2,
    attack: "hammer (d8)",
    description: "Short, bulky, humanoids with tough skin like earth and stone. Dwell in mountains and underground. Do not rely on light, being able to see shapes and heat patterns in darkness. Highly resistant to poison and disease."
  },
  {
    classification: "Elemental, Air",
    name: "",
    str: 11,
    dex: 15,
    wil: 8,
    hp: 16,
    attack: "wind blow (d10)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Huge, living vortexes of whirling air. Lighter creatures are swept away by its presence. Its attacks ignore any worn armor."
  },
  {
    classification: "Elemental, Earth",
    name: "",
    str: 16,
    dex: 6,
    wil: 0,
    hp: 12,
    armor: 3,
    attack: "fists (d12)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Huge humanoid beings made of earth and stone. Create constant earth tremors with their presence. Can meld into the earth and move through it as if swimming."
  },
  {
    classification: "Elemental, Fire",
    name: "",
    str: 0,
    dex: 12,
    wil: 14,
    hp: 16,
    attack: "flare (d10, Blast)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Living columns of pure flame that burn everything in their path. Highly vulnerable to being touched by water or rain. Can scatter their flames, freely changing its form."
  },
  {
    classification: "Elemental, Water",
    name: "",
    str: 15,
    dex: 0,
    wil: 0,
    hp: 12,
    armor: 2,
    attack: "blow (d8)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Huge waves of flowing water. Must stay near a body of water. Envelop victims inside their forms to drown them."
  },
  {
    classification: "Eye of Terror",
    str: 10,
    dex: 8,
    wil: 18,
    hp: 15,
    attack: "bite (d8+d8)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Floating spheres with a large maw, one big central eye, and several small eyes on stalks scattered through the body. Scheming and greedy, lair deep underground. Cancels any magic effect in a nearby range facing its central eye. The eyestalks cast one of those spells each round randomly: (1-Charm, 2-Phobia, 3-Telekinesis, 4-Sleep, 5-Shuffle, 6-Vision)."
  },
  {
    classification: "False Dragon",
    name: "",
    str: 8,
    dex: 14,
    wil: 12,
    hp: 4,
    attack: "sting (d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Tiny winged draconic creatures with a sting-tipped tail and reddish scales. Found in forests and caverns. Capable of communicating telepathically with nearby creatures. Critical Damage: The sting’s poison leaves the victim in a comatose state for 1d6 days."
  },
  {
    classification: "Flail Snail",
    str: 14,
    dex: 6,
    wil: 10,
    hp: 4,
    attack: "tentacles (d8+d8)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Giant snails with heavy, club-like tentacles and a colorful shell. Dwell underground. Its colorful shell can deflect magic, possibly annulling it or reflecting it to its caster."
  },
  {
    classification: "Gargoyle",
    name: "",
    str: 14,
    dex: 6,
    wil: 12,
    hp: 8,
    attack: "claws (d8+d6)",
    description: "Magical creatures that look like monstrous, horned, winged statues. Guard places by standing still to pass like inanimate statues and attacking what comes near. Cannot be charmed and put to sleep."
  },
  {
    classification: "Gelatinous Cube",
    name: "",
    str: 15,
    dex: 6,
    wil: 3,
    hp: 8,
    attack: "devouring touch (d8)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Large cubes of transparent jelly, dwell in dungeons absorbing items and living creatures. Difficult to be detected due to being transparent. Critical Damage: The target is engulfed into the cube and keeps being absorbed."
  },
  {
    classification: "Ghost",
    name: "",
    str: 10,
    dex: 10,
    wil: 15,
    hp: 8,
    attack: "cold touch (d4)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Incorporeal spirits of the restless dead. Avoids direct confrontation, instead it quietly possesses a target and acts through them when possible. Immune to most forms of damage, only susceptible to magic and holy water. Possession: One target must save WIL or be possessed, being controlled by the ghost until it’s somehow driven off."
  },
  {
    classification: "Ghoul",
    name: "",
    str: 14,
    dex: 10,
    wil: 3,
    hp: 6,
    attack: "elongated claws jagged teeth (d8+d6)",
    description: "Grey-skinned man-things wearing shredded clothes, hunkering over the ground. Craves the flesh of the living, as it grows only more powerful with each victim. Critical Damage: target is paralyzed. The wound turns fatal in a day if not treated by a priest or skilled healer. If not burned, the body will rise as a Ghoul."
  },
  {
    classification: "Cloud Giant",
    name: "",
    str: 16,
    dex: 12,
    wil: 18,
    hp: 14,
    attack: "mace (d10+d10)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "20’ tall humanoids with hair and skin in tones of grey and white. House in castles built atop the highest mountains or floating in cloud banks. Cannot be surprised due to its keen sight and smell. Strong winds constantly surround it, impairing projectile attacks."
  },
  {
    classification: "Giant Draco",
    name: "",
    str: 14,
    dex: 14,
    wil: 10,
    hp: 6,
    attack: "bite (d10)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "6’ long carnivorous lizards with skin flaps between legs that allow gliding. Dwell mostly on the surface, but sometimes can be found underground. Hunt by waiting atop tall places and gliding down to surprise targets."
  },
  {
    classification: "Fire Giant",
    name: "",
    str: 17,
    dex: 8,
    wil: 18,
    hp: 13,
    attack: "greatsword (d12+d10)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "16’ tall humanoids with red hair and charcoal skin. Wear heavy armor made of brass, bronze or copper. Lair in fortresses built near volcanoes. Masters of craft and war, know how to forge the finest weaponry. Immune to fire and heat."
  },
  {
    classification: "Giant Flame Lizard",
    name: "",
    str: 14,
    dex: 10,
    wil: 12,
    hp: 8,
    attack: "bite (d8+d6) or fire breath (d6, Blast)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "30’ long grey and red lizards that are sometimes mistaken for dragons. Lair underground where they sleep most of the day, but hunt on the surface. Unharmed by flames and heat. Their eggs can be sold for a high price."
  },
  {
    classification: "Goblin",
    name: "",
    str: 8,
    dex: 12,
    wil: 8,
    hp: 4,
    attack: "dagger (d6) or sling (d4)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Small, grotesque humanoids with skin in earthly tones of green, brown, and grey. Avoid combat, only attacking when in advantage, using hit-and-run tactics. Sometimes are found using dire wolves as mounts."
  },
  {
    classification: "Golem",
    name: "",
    str: 15,
    dex: 6,
    wil: 2,
    hp: 16,
    attack: "cobblestone fists (d10)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "A hulking 9’ tall statue made of clay, mud, and prayer. Mindlessly follows whatever commands given by its master, even after their death. Immune to mundane blades and missile weapons. Damage from fire is Enhanced. If destroyed, the Golem eventually reforms and carries out its previous orders."
  },
  {
    classification: "Green Slime",
    name: "",
    str: 18,
    dex: 6,
    wil: 3,
    hp: 3,
    attack: "acidic touch (d10+d8)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Large blobs of green slime that stick to walls and ceiling. Attack by dropping on top of their victims. The acid corrodes both metal and wood along with the carrier, but cannot affect stone. Consumed flesh becomes more green slime. Immune to all damage except fire. Once stuck on a victim, can only be removed if burned away."
  },
  {
    classification: "Griffon",
    name: "",
    str: 14,
    dex: 15,
    wil: null,
    hp: 7,
    attack: "beak (d8+d8) or claws (d6, Blast)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Ravenous hybrid predators, with the head and wings of an eagle and the lower body of a lion. Fly and attack at astonishing speeds, being able to dive for an attack and fly away before the target can react. Can be used as a mount if taken young and properly trained."
  },
  {
    classification: "Black Hag",
    name: "",
    str: 12,
    dex: null,
    wil: 16,
    hp: 10,
    attack: "talons (d8+d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Hideous, 8’ tall creatures that reassemble female humans of old age with blue-black skin. Their talons and teeth are hard like iron. Dwell in dead forests and swamps, crave eating human flesh. Can cloak their true appearance with an illusory form, and can see through any illusion. Avid magic users, each Hag carries 1d4 random spellbooks."
  },
  {
    classification: "Harpy",
    name: "",
    str: 10,
    dex: 12,
    wil: 14,
    hp: 8,
    attack: "claws (d6+d6) or song (save)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Hideous monstrosities with the body of a giant eagle and a humanoid head. Its movements and flight are clumsy due to its unproportional size. Rely on charmed victims to do anything of note. Charming Song: Anyone who hears the song of a harpy must save WIL or be charmed, following the harpy and defending it from any threat. The charm is broken when the victim leaves the harpy’s presence."
  },
  {
    classification: "Giant Hawk",
    name: "",
    str: 8,
    dex: 15,
    wil: 8,
    hp: 10,
    attack: "talons and beak (d8+d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Large birds of prey, the size of a wolf. Can carry animals up to their size. Hunt animals that they can carry, but might attack humans or greater prey if despaired. Surprise their victims by diving to attack from a great height. Can supposedly be trained to be hunting companions."
  },
  {
    classification: "Hellhound",
    name: "",
    str: 12,
    dex: 15,
    wil: 8,
    hp: 8,
    attack: "bite (d8+d6) or fire breath (d8)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Monstrous, intelligent dogs with the size of a large wolf. Dwell near volcanoes and sometimes accompany other fire-related creatures. Immune to fire and heat, its insides are hot enough to melt iron if it is swallowed. Don’t rely on sight to find its foes, due to its keen sense of smell."
  },
  {
    classification: "Hobgoblin",
    name: "",
    str: 14,
    dex: 8,
    wil: 10,
    hp: 6,
    attack: "mace (d8)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Large and burly relatives of goblins. Dwell in underground fortresses, but frequently march in aboveground campaigns. Strongly lawful and militarized culture, follow orders without question. Automatically succeed in Morale Saves if a commander is present. Trained to fight together, damage dealt is Enhanced if an ally is also engaged with the same enemy."
  },
  {
    classification: "Hooded Men",
    name: "",
    str: 9,
    dex: 12,
    wil: 14,
    hp: 12,
    attack: "leystaff (d8), a Spellbook (Choose one: Charm, Hypnotize, Push/Pull, Shield)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "The Watchers of the Wood; a cult that derive their power from leylines, rune stones, and the like. Critical Damage: leech a part of the victim’s soul (1d4 WIL damage)."
  },
  {
    classification: "Hydra",
    name: "",
    str: 15,
    dex: 12,
    wil: 12,
    hp: 18,
    attack: "bite (d12, Blast)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "A large reptilian creature with nine serpentine heads. Can attack a number of targets equal to the number of heads. Each time it takes damage to STR, loses one head. Severed heads regrow after one turn, recovering 1d4 HP for each head regrown. Fire damage received is Enhanced, and stops head regrowth for a turn."
  },
  {
    classification: "Harpy",
    name: "",
    str: 8,
    dex: 12,
    wil: 16,
    hp: 10,
    attack: "snake bites (d6+d4) or gaze (save)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Magical creatures that look like women with snakes in place of hair. Clever and proud, but reasonable. Will let adventurers go free if they somehow please its ego. Gaze: Anyone who looks directly at the medusa’s face must save WIL or be turned to stone. Averting eyes from the face prevents this effect, but impairs any damage dealt. Targets turned into stone can be recovered by a willing kiss of the medusa, or by being bathed in its blood. The blood of a medusa is only enough to recover a single victim."
  },
  {
    classification: "Mimic",
    name: "",
    str: 13,
    dex: 0,
    wil: 12,
    hp: 9,
    attack: "bite (d12)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Monstrous shape-shifters that take on the form of inanimate objects made of wood and stone. Found only underground. Remain motionless (generally in the form of chests or doors), devouring anything that touches it. The mimic’s saliva is extremely sticky, taking great strength to remove something from its mouth once glued."
  },
  {
    classification: "Mind Flayer",
    name: "",
    str: 8,
    dex: 12,
    wil: 18,
    hp: 12,
    attack: "tentacles (d6+d4), or mind Blast (save)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Humanoid creatures with purple skin and an octopus-like head. Dwell deep underground, plotting to slave humanity. Feed on the brains of other humanoids. Mind Blast: Emits a frequency that affects the brains of nearby creatures, all caught must save WIL or be paralyzed. Critical Damage: The tentacle rips the victim’s brain out of the skull, and the mind lasher eats it, gaining all of the victim’s memories."
  },
  {
    classification: "Minotaur",
    name: "",
    str: 16,
    dex: 0,
    wil: 8,
    hp: 12,
    attack: "axe (d10) or horns (d6+d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "A large, muscular humanoid with the head of a bull. Generally lair in a maze or dungeon, making the whole place its territory. Notably strong, is able to easily break stone, which it uses to alter the environment and separate its foes to kill them one by one. If the minotaur succeeds in a Critical Damage save, it is driven into a bloodthirsty state, enhancing all its attacks and impairing all attacks against it. Only stops when killed or if it no longer sees any foe."
  },
  {
    classification: "Mummy",
    name: "",
    str: 12,
    dex: 8,
    wil: 6,
    hp: 6,
    attack: "infected touch (d10)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Undead humanoids wrapped in funerary bandages. Found in ruins of temples and tombs. The first time anyone sees the mummy, it must save WIL or be paralyzed. The paralysis ends immediately if the mummy attacks or goes out of sight. Critical Damage: The mummy inflicts a disease that rots open wounds, making them impossible to heal normally. Can only be removed by magic."
  },
  {
    classification: "Nightmare",
    name: "",
    str: 15,
    dex: 12,
    wil: 18,
    hp: 8,
    attack: "flaming hooves (d8+d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Intelligent demonic horses with burning-red eyes, smoldering nostrils, and flaming hooves. Constantly breathe a thick cloud of smoke, impairing damage dealt by anyone in melee with the nightmare. Sometimes are used as steeds by other powerful demonic creatures."
  },
  {
    classification: "Ogre",
    name: "",
    str: 16,
    dex: 8,
    wil: 6,
    hp: 6,
    attack: "club (d10)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "10’ tall brute humanoids dressed in animal hides. Mostly live in caves. Mostly antisocial, drive away any other beings from nearby its lair. Easily impressed by shiny materials, carry sacks full of coins with them."
  },
  {
    classification: "Owl Bear",
    name: "",
    str: 16,
    dex: null,
    wil: null,
    hp: 9,
    attack: "beak (d10) or claws (d8+d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Huge, carnivorous bear-like creatures with the face of an owl. Found in dense forests. Excellent trackers, can detect even the slightest signs of prey. Highly territorial, attack anything that comes too close. Critical Damage: Maul the target, crushing armor and tearing a limb apart."
  },
  {
    classification: "Pegasus",
    name: "",
    str: 12,
    dex: 15,
    wil: 15,
    hp: 6,
    attack: "hooves (d6+d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "An intelligent winged horse, wilful and proud. Seen as a symbol of beauty and nobility. Have a rigid sense of morality and can feel if a person has broken it. Will offer to help adventurers as a mount if it judges the person’s cause as noble and just."
  },
  {
    classification: "Purple Worm",
    name: "",
    str: 18,
    dex: 8,
    wil: 6,
    hp: 18,
    attack: "bite (d10+d10), detachment",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Gargantuan worms with bodies more th0an 100’ long and 10’ thick. Burrow in tunnels underground and surface to eat other creatures. Found in deserts and other drylands. Victims that save against Critical Damage caused by the worm are swallowed whole. Anything inside the worm receives d12 acid damage each round. Critical Damage: The target is devoured and crushed inside the worm."
  },
  {
    classification: "Rat",
    name: "",
    str: null,
    dex: 12,
    wil: 8,
    hp: 6,
    attack: "Bite 1d4",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Large rodent equipped with a nasty bite."
  },
  {
    classification: "Red Cap",
    name: "",
    str: null,
    dex: 12,
    wil: 8,
    hp: 6,
    attack: "two sickles (d6+d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Borne from blood left to rot in the fae. Hats colored by blood; they even bathe in blood. Attack travelers, but will ignore those with little to live for, as there is no pleasure in it. Critical Damage: Eviscerate the target, showering in blood, restoring any lost STR and HP."
  },
  {
    classification: "Rust Eater",
    name: "",
    str: 10,
    dex: 12,
    wil: 12,
    hp: 5,
    attack: "bite (d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Armadillo-like creatures with long tails and two long antennae. Feed on rusted metal. Any metal that touches its antennae instantly becomes rust. Relics are partially resistant to this effect. Can smell metal from a long distance."
  },
  {
    classification: "Satyr",
    name: "",
    str: 10,
    dex: 12,
    wil: 16,
    hp: 6,
    attack: "horns (d6) or pipes (save)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Magical humanoids with the legs and horns of a goat that love to dance and drink. Found in deep forests. Highly resistant to magic effects. Pipes: Anyone who hears the music from a satyr's pipes must save WIL or fall asleep, be charmed or frightened. The Satyr chooses which effect when playing the pipes."
  },
  {
    classification: "Giant Scorpion",
    name: "",
    str: 12,
    dex: 12,
    wil: 8,
    hp: 8,
    attack: "claws (d10+d8) or sting (d8)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Huge arachnids, the size of a horse, with pincers and poisonous stingers. Found in drylands and caverns. Highly aggressive, normally attack on sight. Immobilizes its victims with the claws, and then attacks with the sting. Critical Damage: The sting's poison paralyzes the target, killing it in one day if not treated."
  },
  {
    classification: "Shadow",
    name: "",
    str: 8,
    dex: 12,
    wil: 14,
    hp: 6,
    attack: "draining touch (d6, ignores armor)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Incorporeal monsters that look like animated shadows. Unharmed by mundane attacks, sleep or mind control. Critical Damage: The target loses another d4 STR, if reduced to 0 STR, they become a shadow."
  },
  {
    classification: "Shambling Mound",
    name: "",
    str: 15,
    dex: 6,
    wil: 8,
    hp: 9,
    attack: "tendrils (d8+d8)",
    description: "Plant monsters with the rough shape of a 9' tall humanoid made of slimy vegetation. Dwell in dark swamps and damp undergrounds. Damage from mundane weapons is Impaired. Grapples its targets and tries to drown them in water bodies."
  },
  {
    classification: "Skeleton",
    name: "",
    str: 10,
    dex: 13,
    wil: 10,
    hp: 5,
    attack: "rusty sword (d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "If a skeleton is killed and its bones are not scattered, it reforms."
  },
  {
    classification: "Snake Person",
    name: "",
    str: 10,
    dex: 12,
    wil: 14,
    hp: 6,
    attack: "bite (d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Creatures with the body, tail, and head of a giant snake and scaled humanoid torso and arms. Capture other humanoids to be eaten or enslaved by their cruel masters. Dwell in hot jungles. Highly resistant to magic effects. Supposedly can breed with humans, creating hybrids that have the appearance of humans with reptilian eyes and forked tongues."
  },
  {
    classification: "Snake, Pit Viper",
    str: 10,
    dex: 12,
    wil: 10,
    hp: 3,
    attack: "bite (d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "5’ long snakes with greyish scales, found in caves and other dark places. Does not rely on vision, instead, senses its victims by their body heat. Critical Damage: The poison kills the target in a day if an antidote isn’t applied."
  },
  {
    classification: "Snake, Spitting Cobra",
    name: "",
    str: 10,
    dex: 14,
    wil: 10,
    hp: 3,
    attack: "acid spit (d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "3’ long snake with grey and white scales. Notably shy, live in places where they can blend in. Attack from a distance with their acidic spit, always aiming for the head of the target. Critical Damage: The acid corrodes the target’s face, permanently damaging its visage and senses."
  },
  {
    classification: "Sphinx",
    name: "",
    dex: 10,
    wil: 15,
    hp: 12,
    attack: "claws (d8+d6) or roar (save)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Large monsters with bird wings, the body of a lion, and a human face. Collect puzzles, riddles, and obscure knowledge. Might pose riddles to those they meet, attacking and consuming any who cannot give the correct answer. Roar: Anyone who hears the sphinx’s roar must save WIL or flee in fear. Carry 1d4 spellbooks with them, preferring magic related to knowledge or communication but taking any."
  },
  {
    classification: "Giant Phase Spider",
    name: "",
    str: 10,
    dex: 14,
    wil: 12,
    hp: 6,
    attack: "bite (d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "8’ long, black spiders that have the ability to become intangible. Dwell in web-filled lairs and sometimes prey on humans. Can freely shift in and out of existence. When threatened, phases out and only phases in for a second when it attacks. Critical Damage: The poison kills the target in a day if not treated."
  },
  {
    classification: "Titan",
    name: "",
    str: 16,
    dex: 12,
    wil: 18,
    hp: 18,
    attack: "sword (d12+d10)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "20’ tall humanoids of radiant beauty and athletic build. Beneficent of character, but prone to megalomania. Natives of other planes, but sometimes have strongholds in the mortal world. Can levitate at will, with precise control of its movement. Masters of spellcasting, carry 2d6 spellbooks and can always enhance spell effects without risk or need to prepare for it."
  },
  {
    classification: "Triton",
    str: 12,
    dex: 12,
    wil: 12,
    hp: 6,
    attack: "trident (d8)",
    description: "Aquatic humanoids with silvery skin, blue-green hair, and scaled legs ending in fins. Dwell in warm waters both at shallows and at great depths. Extremely proud, consider themselves a better version of any other folk, going through great efforts to prove so. Lair in beautiful castles sculpted from sea rocks and corals, guarded by other sea creatures under their command."
  },
  {
    classification: "Troll",
    name: "",
    str: 14,
    dex: 12,
    wil: 10,
    hp: 6,
    attack: "talons and bite (d10+d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Wicked, 8’ tall humanoids with rubbery bodies. Consume the flesh of other humanoids. Dwell underground, in the barren wilderness, and in the ruined homes of former victims. Fire and acid damage received is Enhanced and stops a troll’s regeneration. When attacked with either of those, the troll fails all morale checks. Regains 3 HP per round, and even severed limbs are reattached. If killed, will regenerate and fight again in an hour."
  },
  {
    classification: "Unicorn",
    name: "",
    str: 10,
    dex: 12,
    wil: 14,
    hp: 6,
    attack: "horn (d10, ignores armor)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Magical horses with a single long horn on its forehead. Timid but proud and wilful, are seen as divine beings. Its hairs are worth small fortunes due to its powerful healing properties. Can teleport to any place in its sight once a day."
  },
  {
    classification: "Vampire",
    name: "",
    str: 14,
    dex: 12,
    wil: 16,
    hp: 12,
    attack: "bite (d10)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Charming, undead creatures that drink the blood of mortals. Act at night and sleep in a coffin during the day. Can change its form to that of a bat. Regeneration: A damaged vampire regains 6 HP when it bites a target that has blood. If killed, it becomes a cloud of gas and retreats to its coffin, reforming at the next nightfall. Can only be killed if exposed to sunlight or if the coffin is destroyed. Critical Damage: The vampire drains the target's essence, dealing d12 damage to WIL. If the target reaches 0 WIL this way, it dies and is raised as a thrall of the vampire."
  },
  {
    classification: "Werewolf",
    name: "",
    str: 15,
    dex: 14,
    wil: 6,
    hp: 8,
    attack: "claws (d6+d6) or bite (d8)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Ferocious humanoid and wolf hybrids that hunt with abandon. Created by a curse being placed in a human or a wolf. Its piercing howls can be heard for miles away and are capable of calling regular wolves to its aid. Mundane attacks are Impaired against the werewolf, but weapons made of silver are Enhanced. Critical Damage: The target becomes infected, transforming into a werewolf by the next full moon."
  },
  {
    classification: "Dire Wolf",
    name: "",
    str: 14,
    dex: 12,
    wil: 0,
    hp: 8,
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Horse-sized, semi-intelligent wolves. Highly territorial, live in forests or mountains and ferociously guard its surroundings. Regular wolves are scared of them but will fight alongside them against invaders. Can be trained like dogs if captured young, but it’s an extremely difficult challenge."
  },
  {
    classification: "Wolf",
    name: "",
    str: 12,
    dex: 14,
    wil: 0,
    hp: 6,
    attack: "bite (d8)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Large canines that dwell primarily in wildlands but occasionally lair in caves. Can be trained like dogs if captured young. When found in packs of at least 4, wolves never fail morale saves."
  },
  {
    classification: "Wood Troll",
    name: "",
    str: 15,
    dex: 12,
    wil: 7,
    hp: 10,
    attack: "claws and bite (d8+d8, Blast)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Large humanoid beings with elongated arms. Live in forests, sharing a deep connection with the vegetation around them. As an action, the troll can eat a handful of moss to fully recover its HP. Critical Damage: Moss and twigs begin growing out of the target’s wounds."
  },
  {
    classification: "Wyvern",
    name: "",
    str: 0,
    dex: 14,
    wil: 0,
    hp: 7,
    attack: "bite (d8+d8) or poisonous sting (d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Winged, two-legged, reptilian monsters with a long tail tipped with a venomous sting. Dwell in any terrain but favor dry cliffs. Shy away from other creatures but attack anything that comes in the vicinity of its nest. Critical Damage: The deadly poison permanently debilitates the target, reducing its maximum STR to the current value."
  },
  {
    classification: "Zombie",
    name: "",
    str: 0,
    dex: 6,
    wil: 3,
    hp: 6,
    attack: "rusted weapon (d6)",
    belongings: ['', '', '', '', '', '', '', '', '', '', '', ''],
    shillings: 0,
    pennies: 0,
    guilders:0,
    description: "Slow, mindless re-animated corpses. Created by wicked wizards to serve as guardians in hordes. Simply attacks anything that comes nearby. Cannot be affected by anything that targets the mind."
  }
];